"""Execute FFmpeg commands generated by the DAG composer."""

import asyncio
import subprocess
from typing import Any, Dict, List


async def renderer(state: Dict[str, Any]) -> Dict[str, Any]:
    """Run rendering steps and return the final output path."""
    logs = state.get("logs", [])
    logs.append("renderer:start")

    dag_plan: List[Dict[str, Any]] = state.get("dag_plan") or []
    if not dag_plan:
        raise ValueError("dag_plan is required for rendering")

    for step in dag_plan:
        command = step["command"]
        await asyncio.to_thread(
            subprocess.run,
            command,
            check=True,
        )

    output_path = state.get("output_target") or ""
    logs.append("renderer:done")
    return {
        "logs": logs,
        "renderer_done": True,
        "output_path": output_path,
    }
